name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Verify and ensure DANE data is available
      run: |
        echo "🔍 Verificando datos del DANE SIPSA..."
        
        # Verificar que el archivo de datos existe
        if [ -f "public/data/dane_sipsa_data.json" ]; then
          echo "✅ Archivo dane_sipsa_data.json encontrado"
          file_size=$(wc -c < "public/data/dane_sipsa_data.json")
          echo "📊 Tamaño del archivo: $file_size bytes"
          
          # Verificar que el archivo tiene contenido válido
          if [ $file_size -gt 1000 ]; then
            echo "✅ El archivo tiene contenido suficiente"
          else
            echo "❌ El archivo parece estar vacío o dañado"
            exit 1
          fi
        else
          echo "❌ Archivo dane_sipsa_data.json no encontrado"
          echo "🔄 Intentando generar datos..."
          
          # Intentar ejecutar el script de Python como fallback
          cd scripts
          python generate_dane_data.py || {
            echo "❌ No se pudieron generar datos del DANE"
            echo "📋 Creando archivo de datos básico para evitar errores..."
            
            # Crear datos básicos si todo falla
            mkdir -p ../public/data
            echo '{"ciudades":[],"productos":[],"metadatos":{"fechaGeneracion":"'$(date -Iseconds)'","fuente":"Datos no disponibles","error":"No se pudieron obtener datos del DANE SIPSA"}}' > ../public/data/dane_sipsa_data.json
            echo "⚠️ Se creó un archivo de datos vacío para evitar errores de carga"
          }
        fi
        
        echo "✅ Verificación de datos completada"
      
    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './dist'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
